# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build

on:
  push:
  pull_request:
    branches:
      - main
  tags:
    - 'v*'
permissions:
  contents: read
  packages: read

jobs:
  build:
    name: 👷 Build Github Actions Enhanced
    runs-on: ubuntu-latest
    steps:
      - name: 📤 Checkout
        uses: actions/checkout@v6
      - name: 🛠️ Setup pnpm
        uses: pnpm/action-setup@9b5745cdf0a2e8c2620f0746130f809adb911c19 #For cache support, update to tag when it is released.
        with:
          cache: true
      - name: 🛠️ Setup Node and Restore NPM Cache
        uses: actions/setup-node@v4
        with:
          node-version: 22.21.x
          cache: pnpm
      - name: 🕒 Version
        shell: pwsh
        run: pnpm version --no-git-tag-version $(Get-Date -Format 'yyyy.M.0-ci.${{ github.run_number }}')
      - name: 🚚 Restore Packages (CI)
        run: pnpm install --frozen-lockfile
      - name: 💄 Prettier Formatting Check
        run: pnpm format-check
      - name: 🧹 Lint
        run: pnpm lint
      - name: 👷 Build
        run: pnpm build
      - name: 🧪 Test
        run: pnpm test
      - name: 📦 Package
        run: pnpm package
      - name: ⬆️ Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: github-actions-enhanced-vsix
          path: github-actions-enhanced-*.vsix
  # publish:
  #   name: 🚀 Publish to VSCode Marketplace
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   steps:
  #     - name: 🤖 Azure Login - Federated Token
  #       if: github.event_name != 'pull_request'
  #       shell: pwsh
  #       run: |
  #         $token = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN
  #         $uri = $env:ACTIONS_ID_TOKEN_REQUEST_URL
  #         $irmParams = @{
  #           Uri = $uri
  #           Authentication = 'Bearer'
  #           Token = (ConvertTo-SecureString -AsPlainText $token)
  #           Body = @{audience = 'api://AzureADTokenExchange' }
  #         }
  #         $jwtResponse = Invoke-Restmethod @irmParams
  #         $fedToken = $jwtResponse.value
  #         if (-not $fedToken) {
  #           throw "Federated token not found in response: $($jwtResponse | ConvertTo-Json -Depth 10)"
  #         }

  #         $azLoginParams = @(
  #           '--service-principal',
  #           '-u', '${{ secrets.AZURE_CLIENT_ID }}',
  #           '-t', '${{ secrets.AZURE_TENANT_ID }}',
  #           '--federated-token', $fedToken
  #         )
  #         & az login @azLoginParams
  #     - name: ⬇️ Download Build Artifact
  #       uses: actions/download-artifact@v6
  #       with:
  #         name: github-actions-enhanced-vsix
  #     - name: 🚀 Publish to VSCode Marketplace
  #       run: npx vsce publish --azure-credential --packagePath github-actions-enhanced-*.vsix