# All releases are done from published GitHub releases to support immutable releases
name: 🚀 Release
on:
  release:
    types: [published]
  workflow_dispatch: # Allow manual triggering for testing, but it will only publish if it's a release event with a tag
    inputs:
      version:
        description: 'Version to publish (must be a tag like v2024.06.0)'
        required: false
permissions:
  id-token: write # Needed for Azure login with federated token
jobs:
  publish:
    name: 🚀 Publish to VS Code Marketplace
    environment:
      name: VS Code Marketplace
      url: https://marketplace.visualstudio.com/items?itemName=justin-grote.github-actions-enhanced
    runs-on: ubuntu-latest
    steps:
      - name: 🤖 Azure Login - Federated Token
        if: github.event_name != 'pull_request'
        shell: pwsh
        run: |
          $token = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN
          if (-not $token) {
            throw "ID token not found in environment variables. Did you set permissions: id-token: write in the workflow?"
          }
          $uri = $env:ACTIONS_ID_TOKEN_REQUEST_URL
          $irmParams = @{
            Uri = $uri
            Authentication = 'Bearer'
            Token = (ConvertTo-SecureString -AsPlainText $token)
            Body = @{audience = 'api://AzureADTokenExchange' }
          }
          $jwtResponse = Invoke-Restmethod @irmParams
          $fedToken = $jwtResponse.value
          if (-not $fedToken) {
            throw "Federated token not found in response: $($jwtResponse | ConvertTo-Json -Depth 10)"
          }

          $azLoginParams = @(
            '--service-principal',
            '--allow-no-subscriptions',
            '-u', '${{ secrets.AZURE_CLIENT_ID }}',
            '-t', '${{ secrets.AZURE_TENANT_ID }}',
            '--federated-token', $fedToken
          )
          & az login @azLoginParams
      - name: 📥 Get VSIX Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          version: tags/${{ github.event.inputs.version || github.event.release.tag_name }}
          file: ^github-actions-enhanced-.*\.vsix$
          regex: true
      - name: 🚀 Publish to VS Code Marketplace
        run: npx @vscode/vsce publish --azure-credential -i github-actions-enhanced-*.vsix